name: smart_text_thief
description: "Smart Text Thief is a revolutionary educational platform that enables instructors to create comprehensive exams faster than traditional methods using AI technology. The system bridges the gap between instructors and students, providing a complete exam lifecycle management solution."

publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  badges: ^3.1.2
  bloc: ^9.2.0
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1
  dio: ^5.9.1
  dropdown_button2: ^2.3.9
  equatable: ^2.0.8
  file_picker: ^10.3.10
  firebase_core: ^4.4.0
  firebase_database: ^12.1.2
  firebase_messaging: ^16.1.1
  
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^20.0.0
  flutter_screenutil: ^5.9.3
  go_router: ^17.1.0
  google_fonts: ^8.0.1
  google_generative_ai: ^0.4.7
  google_mlkit_text_recognition: ^0.15.1
  google_sign_in: ^7.2.0
  googleapis_auth: ^2.0.0
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  icon_broken: ^1.1.0
  icons_plus: ^5.0.0
  intl: ^0.20.2
  no_screenshot: ^0.3.2
  open_file: ^3.5.11
  pdf: ^3.11.3
  sahih_validator: ^2.0.0
  syncfusion_flutter_pdf: ^32.2.3
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/Fonts/
    - assets/Image/
    - assets/service_account.json
    - shorebird.yaml 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Image/s2.png"
  remove_alpha_ios: true
